services:
  - name: backend
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: PORT
        value: 5000

  - name: frontend
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python frontend/app.py"
    envVars:
      - key: PORT
        value: 8000
